### ISSUE TITLE
hfst-ospell segfaults on empty description element in zhfst index file when built with TinyXML

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst-ospell#11]
Steps to reproduce:

1. build a recent version of hfst-ospell (svn HEAD is fine), with zhfst support and using TinyXML2 as the xml parser, install
3. build libvoikko with hfst support, install
5. edit the file $GTHOME/langs/GTLANG/tools/spellcheckers/fstbased/hfst/index.xml so that the description element is empty.
6. build the zhfst file
7. run voikkospell using that zhfst file

Expected result: voikkospell should function normally.

Actual result: voikkospell throws a segmentation fault:

```~
:::gdb
602 else if (strcmp(info->Name(), "description") == 0)
(gdb)

Breakpoint 1, 0x00007fff86c11c00 in strlen ()
(gdb)
Single stepping until exit from function strlen,
which has no line number information.

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x00007fff86c11c00 in strlen ()
(gdb)
```~


This happens around line 602 in the function ZHfstOspellerXmlMetadata::parse_info in ZHfstOspellerXmlMetadata.cc, or in the function ZHfstOspellerXmlMetadata::parse_description in the same file.

Running hfst-ospell through libvoikko is necessary, since hfst-ospell itself doesn't parse the metadata (and has no means of displaying the metadata). It would be good to add a simple option to print metadata in the zhfst file, just to be able to verify the integrity of both hfst-ospell and the zhfst file.

Reported by: snomos

**Comment by flammie** [comment]
Probably should be closed unless someone wants to implement more advanced recovery from this exceptional situation.
