### ISSUE TITLE
hfst-ospell tests fail

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst-ospell#20]
hfst-ospell's "make check" fails randomly on other platforms. I suspect Bash'isms in the test scripts.

Also "make -j8 check" fails even more randomly, because the dependencies between the tests aren't correctly set.

Reported by: TinoDidriksen

**Comment by flammie** [comment]
I actually pushed continuous integration by travis to master few days ago... I think if the tests pass travis they should be considered as passing everywhere, but I don't know how to do alternate archs there...
