### ISSUE TITLE
Suggestion limitation options makes the speller behave wrongly

### ISSUE THREAD

**Issue by snomos** [hfst/hfst-ospell#23]
This is possibly related to issue #17 but the bug seems to affect all options for limiting the returned list of suggestions.

No suggestion output limitations — correct behavior:

`echo vattis | hfst-ospell -S se.zhfst`

Output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    3.683594
gáttis    17.049805
váttes    17.744141
báttis    18.031250
ráttis    19.031250
vadnis    19.031250
láttis    19.031250
váttus    19.031250
váttás    19.031250
vardis    21.031250
...
```

Limit suggestions with --beam/-b — incorrect output:

`echo vattis | hfst-ospell -S -b 5 se.zhfst`

Actual output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
eatnis    33.031250
```

Expected output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    3.683594
gáttis    17.049805
váttes    17.744141
báttis    18.031250
ráttis    19.031250
vadnis    19.031250
láttis    19.031250
váttus    19.031250
váttás    19.031250
```

Limit suggestions with --limit/-n — incorrect output:

`echo vattis | hfst-ospell -S -n 5 se.zhfst`

Actual output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
moattis    32.030273
eatnis    33.031250
feattis    33.031250
hattis    33.031250
```

Expected output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    3.683594
gáttis    17.049805
váttes    17.744141
báttis    18.031250
ráttis    19.031250
```

Limit suggestions with --max-weight/-w — incorrect output:

`echo vattis | hfst-ospell -S -w 5 se.zhfst`

Actual output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    3.683594
gáttis    17.049805
váttes    17.744141
báttis    18.031250
ráttis    19.031250
vadnis    19.031250
láttis    19.031250
váttus    19.031250
váttás    19.031250
vardis    21.031250
addis    21.031250
vavdis    21.031250
váhttis    21.031250
váttos    21.031250
šaddis    21.031250
saddis    23.031250
...
```

Expected output:

```
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    3.683594
```

In the cases using -b/-n the expected best correction is not to be found at all, instead random suggestions with a much higher weight is presented. In the case of -w, the option does not seem to have any effect at all.

The zhfst file used for testing is attached (rename .zip to .zhfst). Tested with the newest hfst-ospell code in github@master on OSX.

[se.zip](https://github.com/hfst/hfst-ospell/files/476256/se.zip)

**Comment by unhammer** [comment]
Is there any chance at all that the weights in the error model are not purely additive?

That would make it impossible to do an incomplete search of the space of suggestions (cutting off early) and still return the globally-best suggestions. E.g. if your fst is the union of
```
[]->o-(a, weight 10)->o-(b, weight -10)->O
[]->o-(a, weight 1)->O
```
and you do nbest=1, then it'll find `a` and set best-so-far to 1 and quit with that result, while the best result was actually ab with w=0.

**Comment by unhammer** [comment]
Actually, they could even all be positive and it still wouldn't work:
```
[]→·-(a, weight 5)->·-(b, weight 0)->O
[]→·-(a, weight 1)->·-(x, weight 9)->O
```

-----

For the `váttis` case, we get to `vá` at weight 1315, and there's a transition into `vát` lowering that to weight 5, but before that happens we've already made a complete correction of `eatmis` at weight 35, so we never get into `vát` if we have nbest=1.

For nbest to cut off, the error model would have to be designed so that situations like this can never arise, but I'm not sure how feasible that is. With a simple example like
```
[]→·-(a, weight 5)->·-(b, weight 0)->O
[]→·-(a, weight 1)->·-(x, weight 9)->O
```
it's easy to push weights forward to get
```
[]→·-(a, weight 5)->·-(b, weight 0)->O
[]→·-(a, weight 10)->·-(x, weight 0)->O
```
(and it seems like openfst has an operation for that: https://github.com/hfst/hfst/blob/4a3be6b7ce6ffc4af05b579ac261639123f50cf2/back-ends/openfstwin/src/include/fst/lookahead-filter.h#L321 ) but what happens when we intersect with the acceptor/lexicon? Will cycles mess things up?

**Comment by unhammer** [comment]
I should've checked earlier: there already is a hfst-push-weights program =D (note that it needs the transducer to be in openfst-tropical (not ol) format and doesn't warn if it's not – you'll instead just get identical output: https://github.com/hfst/hfst/issues/372). 

```
$ hfst-fst2fst -f openfst-tropical  errmodel.default.hfst \
  | hfst-push-weights --push=initial \
  | hfst-fst2fst -w >errmodel-initial-weights.default.hfst

$ echo vattis |hfst-ospell -l acceptor.default.hfst -m errmodel-initial-weights.default.hfst  -S -n1 
"vattis" is NOT in the lexicon:
Corrections for "vattis":
váttis    4.092773
```

Needs more testing, but this seems promising!

**Comment by unhammer** [comment]
I guess this can be closed, fix is in http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2442

**Comment by snomos** [comment]
Also, this issue seems to be similar to issue #17.

**Comment by snomos** [comment]
Closed as per suggestion above.
