### ISSUE TITLE
hfst-ospell-office accepts invalid strings

### ISSUE THREAD

**Issue by snomos** [hfst/hfst-ospell#28]
To repeat:

```
$ echo "10 OarjjeVuodna" | hfst-ospell-office tools/spellcheckers/fstbased/desktop/hfst/smj.zhfst 
@@ hfst-ospell-office is alive
*
```
Compare that with plain `hfst-ospell`:

```
$ echo OarjjeVuodna | hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/smj.zhfst 
"OarjjeVuodna" is NOT in the lexicon:
Corrections for "OarjjeVuodna":
Oarjjevuodna    20.610352
Oarjjevuona    30.897461
Oarjjevuodnan    32.590923
Oarjjevuodnaj    32.590923
oarjjesuodna    34.590923
oarjjevuodna    34.590923
oarjjejuodna    34.590923
oarjje-Vuodna    34.590923
Oarjjevuodna-    20032.591797
```

The bug seems to be located within the case-handling code - mixed-cased strings should only be accepted IFF it matches the lexical form or lexical form + initial upper case.

**Comment by snomos** [comment]
It should be noted that the example in the bug report is taken from SMJ.

**Comment by snomos** [comment]
A consequence of this bug is that correction suggestions for inflected and derived acronyms are usually completely off (example from SME):

```
$ echo "10 AUF´era" | hfst-ospell-office hfst/se.zhfst 
@@ hfst-ospell-office is alive
&	Auera	Auflesa
```

Here is how plain `hfst-ospell` behaves on the same input:

```
$ echo "AUF´era" | hfst-ospell -S hfst/se.zhfst 
"AUF´era" is NOT in the lexicon:
Corrections for "AUF´era":
AU-Bera    37.301758
AU-Gera    37.301758
AU-Nera    37.301758
AU-lera    37.301758
AUF-Vera    37.301758
AUF-ára    37.301758
AUF-ura    37.301758
AUF-lera    37.301758
...
```

Most suggestions are just as irrelevant, but to the end user they will probably seem a bit more relevant, and given some tag weighting (a slight penalty to proper nouns), it should be possible to get the correct suggestion on top.

**Comment by snomos** [comment]
Any progress on this? Here's another example from SMA:

```
$ echo '15 NSR-se' | hfst-ospell-office tools/spellcheckers/fstbased/desktop/hfst/sma.zhfst 
@@ hfst-ospell-office is alive
&	Esrese	Narese	Nerose	Nårese	Norose	Norese	Nerese
```
vs
```
$ echo 'NSR-se' | hfst-ospell -S tools/spellcheckers/fstbased/desktop/hfst/sma.zhfst 
"NSR-se" is NOT in the lexicon:
Corrections for "NSR-se":
NSR:se    14.495081
NBR:se    24.495081
NS:se    24.495081
NSR:sne    24.495081
NSR:ste    24.495081
NSU:se    24.495081
RSR:se    24.495081
SR:se    24.495081
SSR:se    24.495081
NSB:se    24.495081
NOR:se    24.495081
NSD:se    24.495081
NSI:se    24.495081
```

The expected correction `NSR:se` is the first suggestion from hfst-ospell, but is completely missing from hfst-ospell-office.

This bug is causing the speller suggestions to be worse than they could, and we have received a number of feedbacks that the hfst-based speller is worse than the old one. Fixing this bug would help a lot in improving the speller behavior.

`sma.zhfst` file attached for reproducability.

[sma.zhfst.zip](https://github.com/hfst/hfst-ospell/files/2400470/sma.zhfst.zip)

**Comment by snomos** [comment]
For completeness, here is what is produced by voikkospell, with the hfst-ospell backend enabled:

```
$ echo NSR-se | voikkospell -s -d sma -p tools/spellcheckers/fstbased/desktop/hfst/
W: NSR-se
S: NSR:se
S: NBR:se
S: NS:se
S: NSR:sne
S: NSR:ste
```

The output is identical to plain hfst-ospell (and to what we want/expect). Note that libvoikko has its own case handling code, which in this case seems to do a better job.

**Comment by TinoDidriksen** [comment]
The original issue of `OarjjeVuodna` is not a bug. It is expected behavior that mixed caps of an existing word is not criticized. The cmdline flag `--verbatim` changes that behavior.

Commit https://github.com/hfst/hfst-ospell/commit/e272cd260d680e414b0ae68c8c20dc4729c6dce1 solves the other issue that the corrections are made from the mangled input. It is now made from the original input first, and mangled ones come later.

**Comment by snomos** [comment]
Thanks a lot, this fixes the issue. Relevant suggestions are greatly improved now.
