### ISSUE TITLE
Wrong suggestion order from hfst-ospell-office

### ISSUE THREAD

**Issue by snomos** [hfst/hfst-ospell#47]
```
$ echo '10 Jijtjsasse'| hfst-ospell-office sma.zhfst 
@@ hfst-ospell-office is alive
&	Jiutjasse	Ji-jyjsese	Ji-jïjsese	Ji-jijsese	J-jyjsese	J-jïjsese	J-jijsese	Jïjtsasse	Jïjtjese	Jijsese
```

Expected: all hyphenated suggestions coming last, as they are heavily weighted compared to the other suggestions, as seen by plain hfst-ospell (input lower-cased because it doesn't do case folding):

```
$ echo 'jijtjsasse'| hfst-ospell -S sma.zhfst | head -n 14
"jijtjsasse" is NOT in the lexicon:
Corrections for "jijtjsasse":
jïjtsasse    15.497070
jïjtjese    30.594690
jijsese    40.495079
j-jyjsese    20094.496094
j-jïjsese    20094.496094
j-jijsese    20097.496094
```

And with upper-case input (but then missing some suggestions):
```
$ echo 'Jijtjsasse'| hfst-ospell -S sma.zhfst | head -n 10
"Jijtjsasse" is NOT in the lexicon:
Corrections for "Jijtjsasse":
Jiutjasse    43.495079
Ji-jyjsese    10099.495117
Ji-jïjsese    10099.495117
Ji-jijsese    10102.495117
J-jyjsese    20094.496094
J-jïjsese    20094.496094
J-jijsese    20097.496094
```

`divvunspell` does case folding, and returns the following, in the expected order (`divvunspell` presently requires an uncompressed, just zipped zhfst file, thus the slightly different filename):
```
$ echo Jijtjsasse | divvunspell -s -z sma-nocomp.zhfst | head -n 12
Reading from stdin...
Input: Jijtjsasse		[INCORRECT]
Jïjtsasse		15.49707
Jïjtjese		30.59469
Jijsese		40.49508
Jiutjasse		43.49508
Ji-jyjsese		10099.495
Ji-jïjsese		10099.495
Ji-jijsese		10102.495
J-jyjsese		20094.496
J-jïjsese		20094.496
J-jijsese		20097.496
```

The zhfst file is attached.

[sma.zhfst.zip](https://github.com/hfst/hfst-ospell/files/3581411/sma.zhfst.zip)

**Comment by snomos** [comment]
With the new debug option in `hfst-ospell-office`, it is now easier to see what is going on. Consider the following case in SME:

```sh
echo '10 Legenbargu' | hfst-ospell-office -d se.zhfst 
@@ Loading se.zhfst with args max-weight=-1.00, beam=-1.00, time-cutoff=6.00
@@ hfst-ospell-office is alive
&	Legen-bargu (20135.30)	Lege-bargu (20165.30)	Leggenbargu (54.30)	Levgenbargu (57.30)	Liggenbargu (57.30)	Láhkenbargu (57.30)	Leggenbargui (69.30)	Leđgenbargu (69.30)	Leŋgenbargu (69.30)	Leggenbarggu (69.30)
```

That is, the two first suggestions have a very high weight and should not be on top - most likely they should not be given at all, since I asked for 10 suggestions.

Using the same `.zhfst` file, I get the following using `divvunspell`:

```sh
echo Legenbargu | divvunspell suggest -a se.zhfst 
Reading from stdin...
Input: Legenbargu		[INCORRECT]
Leggenbargu		79.3018
Levgenbargu		82.3018
Liggenbargu		87.3018
Láhkenbargu		92.3018
Leđgenbargu		94.3018
Leŋgenbargu		94.3018
Leggenbarggu		99.3018
Leikenbargu		99.3018
Leggenbargui		109.3018
Leggenbárkku		110.3018
```

(weights are different from `hfst-ospell-office` because of additional positional penalties).

Using `hfst-ospell` I get the following:

```sh
echo 'legenbargu' | hfst-ospell -S se.zhfst 
"legenbargu" is NOT in the lexicon:
Corrections for "legenbargu":
leggenbargu    54.301800
levgenbargu    57.301800
liggenbargu    57.301800
láhkenbargu    57.301800
leggenbargui    69.301804
leđgenbargu    69.301804
leŋgenbargu    69.301804
leggenbarggu    69.301804
leikenbargu    69.301804
leggenbárkku    70.301804
leggenbárku    70.301804
leggenbargi    84.301804
loggenbargu    84.301804

echo 'Legenbargu' | hfst-ospell -S se.zhfst 
"Legenbargu" is NOT in the lexicon:
Corrections for "Legenbargu":
Legen-bargu    20135.302734
Lege-bargu    20165.302734
```

The expected output should be strictly ordered according to weight, if identical weight it should be as given by fst (which is usually alphabetically ordered).

The speller file is attached.
[se.zhfst.zip](https://github.com/hfst/hfst-ospell/files/7602590/se.zhfst.zip)

**Comment by TinoDidriksen** [comment]
hfst-ospell-office's output is from multiple sources.

`Legen-bargu (20135.30)	Lege-bargu (20165.30)` are based on the verbatim input `Legenbargu`.

`Leggenbargu (54.30)	Levgenbargu (57.30)	...` are based on the case-folded `legenbargu` and then recased to first-upper.

I would argue suggestions generated from the verbatim input *should* come before suggestions generated from mangled input, but that is a considerable weight difference.

Maybe something like giving the mangled outputs increasing penalties before doing a global sort. That would still give the desired output for this case, but preserve the semantic that verbatims ought to be worth more.

**Comment by TinoDidriksen** [comment]
Implemented, and also added the mangling level to the debug output. Did not close the issue, as this behavior is up for debate.

**Comment by snomos** [comment]
Here's another case in support of the change, this time from SMA.

- input: `Jalh`
- expected correction: `Jallh`

Using `hfst-ospell-office` before the change (output linewrapped for better readability):

```sh
echo '25 Jalh' | hfst-ospell-office -d sma.zhfst 
@@ Loading sma.zhfst with args max-weight=-1.00, beam=-1.00, time-cutoff=6.00
@@ hfst-ospell-office is alive
&	Aalh (32.50)	Jaah (37.50)	Jaloh (42.50)	Jauh (42.50)	Jayh (42.50)\
	Valh (42.50)	Lalh (42.50)	Jarlh (42.50)	Janh (42.50)	Jarh (42.50)\
	Julh (42.50)	Jalo (42.50)	Jillh (52.50)	Ji:h (87.50)	J-aalh (10109.50)\
	Jallh (20.67)	Jah (30.65)	Javlh (32.50)	Jaljh (32.50)	Jalkh (32.50)\
	Jïllh (42.50)	Jollh (42.50)	J-aalh (20109.50)
```

The expected correction *has the lowest weight*, but is suggestion nr **16**.

Using the newest/updated `hfst-ospell-office`:

```sh
echo '25 Jalh' | hfst-ospell-office -d sma.zhfst 
@@ Loading sma.zhfst with args max-weight=-1.00, beam=-1.00, time-cutoff=6.00
@@ hfst-ospell-office is alive
&	Jallh (20.67;1)	Aalh (32.50;0)	Jah (30.65;1)	Aalh (32.50;1)	Jaljh (32.50;1)\
	Jalkh (32.50;1)	Javlh (32.50;1)	Jaah (37.50;0)	Jalo (42.50;0)	Jaloh (42.50;0)\
	Janh (42.50;0)	Jarh (42.50;0)	Jarlh (42.50;0)	Jauh (42.50;0)	Jayh (42.50;0)\
	Julh (42.50;0)	Lalh (42.50;0)	Valh (42.50;0)	Jollh (42.50;1)	Jïllh (42.50;1)\
	Lalh (42.50;1)	Valh (42.50;1)	Jillh (52.50;0)	Ji:h (87.50;0)	J-aalh (10109.50;0)
```

Now the expected correction is on top.

The speller [sma.zhfst](https://github.com/hfst/hfst-ospell/files/7606960/sma.zhfst.zip) file is attached.
